### ISSUE TITLE
Feature proposal: Text when not playing music

### ISSUE THREAD

**Issue by simonszu** [gmccoy42/GPMDP-PlayerInfo#3]
Just a little cosmetic issue: I have integrated your script into my i3blocks configuration, and set the `label` to a headphones icon. This is cool when GPMDP is actually playing music. When there is no music playing, this script outputs nothing, but i3blocks is still displaying the headphones icon with some whitespace next to it between two separators, which looks funny. So i would suggest to change the output of this script to something like "Not playing" when GPMDP actually isn't playing - maybe configurable via command line flag, so that this message is optional for people with a similar setup like me.

**Comment by gregmccoy** [comment]
Good idea, Adding it with the flag `--not-playing`
https://github.com/gregmccoy/GPMDP-PlayerInfo/commit/4aba6d5e52533289ef5baba24d91e5c29a76ed89

**Comment by simonszu** [comment]
Cool, thanks.
